[tool.poetry]
name = "railos-consist"
version = "1.2.0"
description = ""
authors = ["Kristian Zarebski <krizar312@gmail.com>"]
readme = "README.md"
packages = [{include = "railos_consist"}]

[tool.poetry.dependencies]
python = "^3.10,<3.12"
pysimplegui = "^4.60.4"
railostools = {git = "https://github.com/Railway-Op-Sim/railostools.git", subdirectory="python", tag="v0.5.7"}
pyperclip = "^1.8.2"


[tool.poetry.group.dev.dependencies]
black = {version = "^23.1a1", allow-prereleases = true}
pyinstaller = "^5.7.0"
pytest = "^7.2.1"
pytest-cov = "^4.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
railosconsist = 'railos_consist.railosconsist:launch_application'
