[tool.poetry]
name = "railos-consist"
version = "0.1.0"
description = ""
authors = ["Kristian Zarebski <krizar312@gmail.com>"]
readme = "README.md"
packages = [{include = "railos_consist"}]

[tool.poetry.dependencies]
python = "^3.10,<3.12"
pysimplegui = "^4.60.4"
pandas = "^1.5.3"
railostools = {git = "https://github.com/Railway-Op-Sim/railostools.git", subdirectory="python"}
pyperclip = "^1.8.2"


[tool.poetry.group.dev.dependencies]
black = {version = "^23.1a1", allow-prereleases = true}
pyinstaller = "^5.7.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
