name: RailOSConsist
on:
  push:
    branches: ["main"]
jobs:
  testing:
    runs-on: windows-latest
    name: RailOS Consist Testing
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          architecture: 'x64'
      - name: Setup Poetry
        run: |
          python -m pip install poetry
          python -m poetry install
      - name: Run Unit Tests
        run: |
          LC_ALL="UTF-8" LC_CTYPE="UTF-8" poetry install
          poetry run pytest --cov=railos_consists
        shell: bash
      - name: Get Previous tag
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"

      - name: Build application
        run: poetry run pyinstaller --clean -y RailOSConsist.spec
        shell: bash
